image: golang:1.11

cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - build
  - test
  - install

unit_tests:
  stage: test
  script:
    - go test ./...

lint_code:
  image: golangci/golangci-lint
  stage: test
  script:
    - make lint

build:
  stage: build
  script:
    - go build ./...

install:
  stage: install
  script:
    - make install
