image: golang:1.13

cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test
  - build
  - push
  - deploy
  - smoke-test
  - seed

unit_tests:
  stage: test
  coverage: '/^coverage:\s(\d+(?:\.\d+)?%)/'
  variables:
    SignerName: "jack"
    SignerPasswd: "password"
  script:
    - go test -mod=readonly -v -coverprofile .testCoverage.txt ./...

lint_code:
  image: golangci/golangci-lint
  stage: test
  script:
    - make lint-verbose

integration:test:
  image: cbarraford/golang-ruby
  stage: test
  script:
    - make -C ./test/integration install setup run wait-for-blockchain test-internal

build:test:
  stage: test
  image: docker:stable
  except:
    - master
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git
    - pip install awscli
  environment:
    name: develop
  script: make docker-aws-build

# Build docker image
build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git
    - make docker-gitlab-login
  environment:
    name: develop
  script:
    - make docker-gitlab-build
    - make docker-gitlab-push

push:
  stage: push
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    GIT_STRATEGY: none
  before_script:
    - apk update
    - apk add python py-pip make git
    - make docker-gitlab-login
  script:
    - make docker-gitlab-pull
    - BUILD_FLAG=develop make docker-gitlab-tag-build-flag
    - BUILD_FLAG=develop make docker-gitlab-push-build-flag












deploy:develop:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git
    - pip install awscli
    - make aws-login
  except:
    - schedules
  environment:
    name: develop
  script: make aws-ecs-deploy
  only:
    - master

smoke-test:develop:
  stage: smoke-test
  image: golang:1.13
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - export GOBIN=$GOPATH/bin
  except:
    - schedules
  environment:
    name: develop
  script: make smoke-test
  only:
    - master
  when: manual

seed:develop:
  stage: seed
  image: golang:1.13
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - export GOBIN=$GOPATH/bin
  except:
    - schedules
  environment:
    name: develop
  script: make seed
  only:
    - master
  when: manual

deploy:staging:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git
    - pip install awscli
    - make aws-login
  environment:
    name: staging
  script: make aws-ecs-deploy
  only:
    - schedules

smoke-test:staging:
  stage: smoke-test
  image: golang:1.13
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - export GOBIN=$GOPATH/bin
  except:
    - schedules
  environment:
    name: staging
  script: make smoke-test
  only:
    - schedules

seed:staging:
  stage: seed
  image: golang:1.13
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - export GOBIN=$GOPATH/bin
  except:
    - schedules
  environment:
    name: staging
  script: make seed
  only:
    - schedules

deploy:production:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git
    - pip install awscli
    - make aws-login
  environment:
    name: production
  script: make aws-ecs-deploy
  only:
    - master
  when: manual
