image: golang:1.11

cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test
  - integration
  - build

unit_tests:
  stage: test
  coverage: '/^coverage:\s(\d+(?:\.\d+)?%)/'
  script:
    - go test -mod=readonly -v -coverprofile .testCoverage.txt ./...

lint_code:
  image: golangci/golangci-lint
  stage: test
  script:
    - make lint

integration_tests:
  image: cbarraford/golang-ruby
  stage: integration
  script:
    - make -C ./tests/integration install setup run wait-for-blockchain test-internal

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  before_script:
    - export REPOSITORY_URL="526267067157.dkr.ecr.ap-southeast-2.amazonaws.com/statechain"
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
  script:
    - $(aws ecr get-login --no-include-email --region ap-southeast-2)
    - docker build -t $REPOSITORY_URL .
    - docker push $REPOSITORY_URL
  only:
    - master
  tags:
    - docker
