image: golang:1.13

cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test
  - deploy

unit_tests:
  stage: test
  coverage: '/^coverage:\s(\d+(?:\.\d+)?%)/'
  variables:
    SignerName: "jack"
    SignerPasswd: "password"
  script:
    - go test -mod=readonly -v -coverprofile .testCoverage.txt ./...

lint_code:
  image: golangci/golangci-lint
  stage: test
  script:
    - make lint-verbose

trigger_build_and_deploy:
  stage: deploy
  only:
    - master
  script:
    - "curl -X POST -F token=$TOKEN -F ref=master https://gitlab.com/api/v4/projects/14289231/trigger/pipeline"
