image: golang:1.11

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - build
  - test
  - install

unit_tests:
  stage: test
  script:
    - mkdir -p .cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"
    - go test ./...

lint_code:
  image: golangci/golangci-lint
  stage: test
  script:
    - make lint

build:
  stage: build
  script:
    - go build ./...

install:
  stage: install
  script:
    - make install
