image: golang:1.13

cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test
  - integration

unit_tests:
  stage: test
  coverage: '/^coverage:\s(\d+(?:\.\d+)?%)/'
  script:
    - go test -mod=readonly -v -coverprofile .testCoverage.txt ./...

lint_code:
  image: golangci/golangci-lint
  stage: test
  script:
    - make lint

integration_tests:
  image: cbarraford/golang-ruby
  stage: integration
  script:
    - make -C ./tests/integration install setup run wait-for-blockchain test-internal
