cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test
  - integration
  - build
  - deploy

unit:test:
  stage: test
  image: golang:1.13
  coverage: '/^coverage:\s(\d+(?:\.\d+)?%)/'
  script:
    - go test -v -coverprofile .testCoverage.txt ./...

lint:
  image: golangci/golangci-lint
  stage: test
  script:
    - make lint

integration:
  image: cbarraford/golang-ruby
  stage: integration
  script:
    - make -C ./tests/integration install setup run wait-for-blockchain test-internal

build:
  stage: build
  image: docker:stable
  except:
    - master
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git
    - pip install awscli
  environment:
    name: develop
  script: make -C ./build/service-node build




#trigger_build_and_deploy:
#  stage: deploy
#  only:
#    - master
#  script:
#    - "curl -X POST -F token=$TOKEN -F ref=master https://gitlab.com/api/v4/projects/14289231/trigger/pipeline"
