cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test
  - integration
  - deploy

unit:test:
  stage: test
  image: golang:1.13
  coverage: '/^coverage:\s(\d+(?:\.\d+)?%)/'
  script:
    - go test -v -coverprofile .testCoverage.txt ./...

lint:
  image: golangci/golangci-lint
  stage: test
  script:
    - make lint

integration:tests:
  image: cbarraford/golang-ruby
  stage: integration
  script:
    - make -C ./tests/integration install setup run wait-for-blockchain test-internal

trigger_build_and_deploy:
  stage: deploy
  only:
    - master
  script:
    - "curl -X POST -F token=$TOKEN -F ref=master https://gitlab.com/api/v4/projects/14289231/trigger/pipeline"
