image: golang:1.11

cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test
  - integration

unit_tests:
  stage: test
  script:
    - go test ./...

lint_code:
  image: golangci/golangci-lint
  stage: test
  script:
    - make lint

integration_tests:
  image: docker:latest
  stage: integration
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - docker info
    - docker build -t statechain tests/integration
  script:
    - make -C tests/integration test
