image: golang:1.13

cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"
  - go get mvdan.cc/gofumpt

stages:
  - deploy

deploy:
  stage: deploy
  image: docker/compose:alpine-1.25.4
  only:
    - schedules
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk add sudo jq python git py-pip make bash curl python-dev
    - pip install --upgrade pip && pip install awscli requests boto3 
    - make aws-ci-login
  script:
    - cd $CI_PROJECT_DIR/build/docker/${THORNODE_ENV}
    - python update_testnet_ip.py
