cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test
  - deploy

unit:test:
  stage: test
  image: golang:1.13
  coverage: '/^coverage:\s(\d+(?:\.\d+)?%)/'
  script:
    - go test -v -coverprofile .testCoverage.txt ./...

lint:test:
  image: golangci/golangci-lint
  stage: test
  script:
    - make lint

integration:test:
  image: cbarraford/golang-ruby
  stage: test
  script:
    - make -C ./tests/integration install setup run wait-for-blockchain test-internal

build:test:
  stage: test
  image: docker:stable
  except:
    - master
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git
    - pip install awscli
  environment:
    name: develop
  script: make -C ./build/service-node build

deploy:develop:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git
    - pip install awscli
  except:
    - schedules
  environment:
    name: develop
  script: make -C ./build/service-node deploy
  only:
    - master

deploy:staging:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git
    - pip install awscli
  environment:
    name: staging
  script: ENV=STAGING make deploy
  only:
    - schedules

deploy:production:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git
    - pip install awscli
  except:
    - schedules
  environment:
    name: production
  script: ENV=PRODUCTION make deploy
  only:
    - master
  when: manual
