image: golang:1.11

cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test
  - install

unit_tests:
  stage: test
  coverage: '^coverage:\s(\d+(?:\.\d+)?%)'
  script:
    - go test ./...

lint_code:
  image: golangci/golangci-lint
  stage: test
  script:
    - make lint

install:
  stage: install
  script:
    - make install
