image: golang:1.11

cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test
  - integration
  - docs

unit_tests:
  stage: test
  coverage: '/^coverage:\s(\d+(?:\.\d+)?%)/'
  script:
    - go test ./...

lint_code:
  image: golangci/golangci-lint
  stage: test
  script:
    - make lint

integration_tests:
  image: cbarraford/golang-ruby
  stage: integration
  script:
    - make -C ./tests/integration install setup run wait-for-blockchain test-internal

docs:
  image: cbarraford/apib2swagger
  stage: docs
  script:
    - -i ./docs/api/blueprint.apib -o swagger.json
