version: '3'

services:
  observer_1:
    hostname: observer_1
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/observer.Dockerfile
    image: thornode-observer
    restart: unless-stopped
    environment:
      CHAIN_HOST: thor-api_1:1317
    entrypoint:
      /docker/scripts/observer.sh
    depends_on:
      - thor-api_1
    links:
      - thor-api_1
    volumes:
      - ${PWD}:/docker
      - ${HOME}/.thornode/genesis_1/.ssd:/root/.ssd
      - ${HOME}/.thornode/genesis_1/.sscli:/root/.sscli
    command: ["observed", "-c", "/etc/observe/observed/config.json"]

  signer_1:
    hostname: signer_1
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/signer.Dockerfile
    image: thornode-signer
    restart: unless-stopped
    environment:
      CHAIN_HOST: thor-api_1:1317
      RPC_HOST: thor-daemon_1:26657
    entrypoint:
      /docker/scripts/signer.sh
    depends_on:
      - thor-api_1
    links:
      - thor-api_1
    volumes:
      - ${PWD}:/docker
      - /tmp/genesis:/tmp/shared
      - ${HOME}/.thornode/genesis_1/keys:/root/.signer
    command: ["signd", "-c", "/etc/observe/signd/config.json"]

  thor-daemon_1:
    hostname: thor-daemon_1
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/statechain.Dockerfile
    image: thornode-statechain
    environment:
      NODES: 4
      SEED: thor-daemon_1
    entrypoint:
      /docker/scripts/genesis.sh
    volumes:
      - /tmp/genesis:/tmp/shared
      - ${PWD}:/docker
      - ${HOME}/.thornode/genesis_1/.ssd:/root/.ssd
      - ${HOME}/.thornode/genesis_1/.sscli:/root/.sscli
      - ${HOME}/.thornode/genesis_1/keys:/root/.signer
    command: ["ssd", "start", "--rpc.laddr", "tcp://0.0.0.0:26657"]

  thor-api_1:
    hostname: thor-api_1
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/statechain.Dockerfile
    depends_on:
      - thor-daemon_1
    links:
      - thor-daemon_1
    image: thornode-statechain
    environment:
      CHAIN_DAEMON: thor-daemon_1:26657
    entrypoint:
      /docker/scripts/rest.sh
    volumes:
      - ${PWD}:/docker
      - ${HOME}/.thornode/genesis_1/.ssd:/root/.ssd
      - ${HOME}/.thornode/genesis_1/.sscli:/root/.sscli
    command: ["sscli", "rest-server", "--chain-id", "statechain", "--laddr", "tcp://0.0.0.0:1317", "--node", "tcp://thor-daemon:26657"]


  observer_2:
    hostname: observer_2
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/observer.Dockerfile
    image: thornode-observer
    restart: unless-stopped
    environment:
      CHAIN_HOST: thor-api_2:1317
    entrypoint:
      /docker/scripts/observer.sh
    depends_on:
      - thor-api_2
    links:
      - thor-api_2
    volumes:
      - ${PWD}:/docker
      - ${HOME}/.thornode/genesis_2/.ssd:/root/.ssd
      - ${HOME}/.thornode/genesis_2/.sscli:/root/.sscli
    command: ["observed", "-c", "/etc/observe/observed/config.json"]

  signer_2:
    hostname: signer_2
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/signer.Dockerfile
    image: thornode-signer
    restart: unless-stopped
    environment:
      CHAIN_HOST: thor-api_2:1317
      RPC_HOST: thor-daemon_2:26657
    entrypoint:
      /docker/scripts/signer.sh
    depends_on:
      - thor-api_2
    links:
      - thor-api_2
    volumes:
      - ${PWD}:/docker
      - /tmp/genesis:/tmp/shared
      - ${HOME}/.thornode/genesis_2/keys:/root/.signer
    command: ["signd", "-c", "/etc/observe/signd/config.json"]

  thor-daemon_2:
    hostname: thor-daemon_2
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/statechain.Dockerfile
    image: thornode-statechain
    environment:
      NODES: 4
      SEED: thor-daemon_1
    entrypoint:
      /docker/scripts/genesis.sh
    volumes:
      - /tmp/genesis:/tmp/shared
      - ${PWD}:/docker
      - ${HOME}/.thornode/genesis_2/.ssd:/root/.ssd
      - ${HOME}/.thornode/genesis_2/.sscli:/root/.sscli
      - ${HOME}/.thornode/genesis_2/keys:/root/.signer
    command: ["ssd", "start", "--rpc.laddr", "tcp://0.0.0.0:26657"]

  thor-api_2:
    hostname: thor-api_2
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/statechain.Dockerfile
    depends_on:
      - thor-daemon_2
    links:
      - thor-daemon_2
    image: thornode-statechain
    environment:
      CHAIN_DAEMON: thor-daemon_2:26657
    entrypoint:
      /docker/scripts/rest.sh
    volumes:
      - ${PWD}:/docker
      - ${HOME}/.thornode/genesis_2/.ssd:/root/.ssd
      - ${HOME}/.thornode/genesis_2/.sscli:/root/.sscli
    command: ["sscli", "rest-server", "--chain-id", "statechain", "--laddr", "tcp://0.0.0.0:1317", "--node", "tcp://thor-daemon:26657"]


  observer_3:
    hostname: observer_3
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/observer.Dockerfile
    image: thornode-observer
    restart: unless-stopped
    environment:
      CHAIN_HOST: thor-api_3:1317
    entrypoint:
      /docker/scripts/observer.sh
    depends_on:
      - thor-api_3
    links:
      - thor-api_3
    volumes:
      - ${PWD}:/docker
      - ${HOME}/.thornode/genesis_3/.ssd:/root/.ssd
      - ${HOME}/.thornode/genesis_3/.sscli:/root/.sscli
    command: ["observed", "-c", "/etc/observe/observed/config.json"]

  signer_3:
    hostname: signer_3
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/signer.Dockerfile
    image: thornode-signer
    restart: unless-stopped
    environment:
      CHAIN_HOST: thor-api_3:1317
      RPC_HOST: thor-daemon_3:26657
    entrypoint:
      /docker/scripts/signer.sh
    depends_on:
      - thor-api_3
    links:
      - thor-api_3
    volumes:
      - ${PWD}:/docker
      - /tmp/genesis:/tmp/shared
      - ${HOME}/.thornode/genesis_3/keys:/root/.signer
    command: ["signd", "-c", "/etc/observe/signd/config.json"]

  thor-daemon_3:
    hostname: thor-daemon_3
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/statechain.Dockerfile
    image: thornode-statechain
    environment:
      NODES: 4
      SEED: thor-daemon_1
    entrypoint:
      /docker/scripts/genesis.sh
    volumes:
      - /tmp/genesis:/tmp/shared
      - ${PWD}:/docker
      - ${HOME}/.thornode/genesis_3/.ssd:/root/.ssd
      - ${HOME}/.thornode/genesis_3/.sscli:/root/.sscli
      - ${HOME}/.thornode/genesis_3/keys:/root/.signer
    command: ["ssd", "start", "--rpc.laddr", "tcp://0.0.0.0:26657"]

  thor-api_3:
    hostname: thor-api_3
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/statechain.Dockerfile
    depends_on:
      - thor-daemon_3
    links:
      - thor-daemon_3
    image: thornode-statechain
    environment:
      CHAIN_DAEMON: thor-daemon_3:26657
    entrypoint:
      /docker/scripts/rest.sh
    volumes:
      - ${PWD}:/docker
      - ${HOME}/.thornode/genesis_3/.ssd:/root/.ssd
      - ${HOME}/.thornode/genesis_3/.sscli:/root/.sscli
    command: ["sscli", "rest-server", "--chain-id", "statechain", "--laddr", "tcp://0.0.0.0:1317", "--node", "tcp://thor-daemon:26657"]


  observer_4:
    hostname: observer_4
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/observer.Dockerfile
    image: thornode-observer
    restart: unless-stopped
    environment:
      CHAIN_HOST: thor-api_4:1317
    entrypoint:
      /docker/scripts/observer.sh
    depends_on:
      - thor-api_4
    links:
      - thor-api_4
    volumes:
      - ${PWD}:/docker
      - ${HOME}/.thornode/genesis_4/.ssd:/root/.ssd
      - ${HOME}/.thornode/genesis_4/.sscli:/root/.sscli
    command: ["observed", "-c", "/etc/observe/observed/config.json"]

  signer_4:
    hostname: signer_4
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/signer.Dockerfile
    image: thornode-signer
    restart: unless-stopped
    environment:
      CHAIN_HOST: thor-api_4:1317
      RPC_HOST: thor-daemon_4:26657
    entrypoint:
      /docker/scripts/signer.sh
    depends_on:
      - thor-api_4
    links:
      - thor-api_4
    volumes:
      - ${PWD}:/docker
      - /tmp/genesis:/tmp/shared
      - ${HOME}/.thornode/genesis_4/keys:/root/.signer
    command: ["signd", "-c", "/etc/observe/signd/config.json"]

  thor-daemon_4:
    hostname: thor-daemon_4
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/statechain.Dockerfile
    image: thornode-statechain
    environment:
      NODES: 4
      SEED: thor-daemon_1
    entrypoint:
      /docker/scripts/genesis.sh
    volumes:
      - /tmp/genesis:/tmp/shared
      - ${PWD}:/docker
      - ${HOME}/.thornode/genesis_4/.ssd:/root/.ssd
      - ${HOME}/.thornode/genesis_4/.sscli:/root/.sscli
      - ${HOME}/.thornode/genesis_4/keys:/root/.signer
    command: ["ssd", "start", "--rpc.laddr", "tcp://0.0.0.0:26657"]

  thor-api_4:
    hostname: thor-api_4
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/statechain.Dockerfile
    depends_on:
      - thor-daemon_4
    links:
      - thor-daemon_4
    image: thornode-statechain
    environment:
      CHAIN_DAEMON: thor-daemon_4:26657
    entrypoint:
      /docker/scripts/rest.sh
    volumes:
      - ${PWD}:/docker
      - ${HOME}/.thornode/genesis_4/.ssd:/root/.ssd
      - ${HOME}/.thornode/genesis_4/.sscli:/root/.sscli
    command: ["sscli", "rest-server", "--chain-id", "statechain", "--laddr", "tcp://0.0.0.0:1317", "--node", "tcp://thor-daemon:26657"]

