version: '3'

services:
  observer:
    hostname: observer
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/observer.Dockerfile
    image: registry.gitlab.com/thorchain/bepswap/thornode-observer
    restart: unless-stopped
    environment:
      CHAIN_HOST: thor-api:1317
    entrypoint:
      /docker/scripts/observer.sh
    depends_on:
      - thor-api
    links:
      - thor-api
    volumes:
      - ${PWD}:/docker
      - ${HOME}/.thornode/standalone/.thord:/root/.thord
      - ${HOME}/.thornode/standalone/.thorcli:/root/.thorcli
    command: ["observed", "-c", "/etc/observe/observed/config.json"]

  signer:
    hostname: signer
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/signer.Dockerfile
    image: registry.gitlab.com/thorchain/bepswap/thornode-signer
    restart: unless-stopped
    environment:
      CHAIN_HOST: thor-api:1317
      RPC_HOST: thor-daemon:26657
    entrypoint:
      /docker/scripts/signer.sh
    depends_on:
      - thor-api
    links:
      - thor-api
    volumes:
      - ${PWD}:/docker
      - /tmp/genesis:/tmp/shared
      - ${HOME}/.thornode/standalone/keys:/root/.signer
    command: ["signd", "-c", "/etc/observe/signd/config.json"]

  thor-daemon:
    hostname: thor-daemon
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/statechain.Dockerfile
    image: registry.gitlab.com/thorchain/bepswap/thornode-statechain
    environment:
      NODES: 1
      SEED: thor-daemon
    expose:
      - "26657"
    entrypoint:
      /docker/scripts/genesis.sh
    volumes:
      - /tmp/genesis:/tmp/shared
      - ${PWD}:/docker
      - ${HOME}/.thornode/standalone/.thord:/root/.thord
      - ${HOME}/.thornode/standalone/.thorcli:/root/.thorcli
      - ${HOME}/.thornode/standalone/keys:/root/.signer
    command: ["thord", "start", "--rpc.laddr", "tcp://0.0.0.0:26657"]

  thor-api:
    hostname: thor-api
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/statechain.Dockerfile
    depends_on:
      - thor-daemon
    links:
      - thor-daemon
    image: registry.gitlab.com/thorchain/bepswap/thornode-statechain
    environment:
      CHAIN_DAEMON: thor-daemon:26657
    expose:
      - "1317"
    entrypoint:
      /docker/scripts/rest.sh
    volumes:
      - ${PWD}:/docker
      - ${HOME}/.thornode/standalone/.thord:/root/.thord
      - ${HOME}/.thornode/standalone/.thorcli:/root/.thorcli
    command: ["thorcli", "rest-server", "--chain-id", "statechain", "--laddr", "tcp://0.0.0.0:1317", "--node", "tcp://thor-daemon:26657"]
