version: '3'

services:
  observer:
    hostname: observer
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/observer.Dockerfile
    image: thornode-observer
    restart: unless-stopped
    environment:
      CHAIN_HOST: thor-api:1317
    entrypoint:
      /docker/scripts/observer.sh
    depends_on:
      - thor-api
    links:
      - thor-api
    volumes:
      - ${PWD}:/docker
      - ${HOME}/.thornode/validator/.ssd:/root/.ssd
      - ${HOME}/.thornode/validator/.sscli:/root/.sscli
    command: ["observed", "-c", "/etc/observe/observed/config.json"]

  signer:
    hostname: signer
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/signer.Dockerfile
    image: thornode-signer
    restart: unless-stopped
    environment:
      CHAIN_HOST: thor-api:1317
      RPC_HOST: thor-daemon:26657
    entrypoint:
      /docker/scripts/signer.sh
    depends_on:
      - thor-api
    links:
      - thor-api
    volumes:
      - ${PWD}:/docker
      - /tmp/genesis:/tmp/shared
      - ${HOME}/.thornode/validator/keys:/root/.signer
    command: ["signd", "-c", "/etc/observe/signd/config.json"]

  thor-daemon:
    hostname: thor-daemon
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/statechain.Dockerfile
    image: thornode-statechain
    entrypoint:
      /docker/scripts/genesis.sh
    volumes:
      - /tmp/genesis:/tmp/shared
      - ${PWD}:/docker
      - ${HOME}/.thornode/validator/.ssd:/root/.ssd
      - ${HOME}/.thornode/validator/.sscli:/root/.sscli
      - ${HOME}/.thornode/validator/keys:/root/.signer
    command: ["ssd", "start", "--rpc.laddr", "tcp://0.0.0.0:26657"]

  thor-api:
    hostname: thor-api
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/statechain.Dockerfile
    depends_on:
      - thor-daemon
    links:
      - thor-daemon
    image: thornode-statechain
    environment:
      CHAIN_DAEMON: thor-daemon:26657
    entrypoint:
      /docker/scripts/rest.sh
    volumes:
      - ${PWD}:/docker
      - ${HOME}/.thornode/validator/.ssd:/root/.ssd
      - ${HOME}/.thornode/validator/.sscli:/root/.sscli
    command: ["sscli", "rest-server", "--chain-id", "statechain", "--laddr", "tcp://0.0.0.0:1317", "--node", "tcp://thor-daemon:26657"]

  binance:
    hostname: binance-fullnode
    image: varnav/binance-node
    restart: unless-stopped
    environment:
      BNET: "prod"
    ports:
      - "27146:27146" 
      - "27147:27147"
      - "26660:26660"
    ulimits:
    nofile:
      soft: "16000"
      hard: "16000"
    security-opt: no-new-privileges
    volumes:
      - ${HOME}/.thornode/binance:/opt/bnbchaind
